### ISSUE TITLE
Excel version compatibility issues

### ISSUE THREAD

**Issue by achafetz** [pepfar-datim/data-pack-commons#30]
@jacksonsj @jason-p-pickering @sam-bao 

Unfortunately it looks like we have some significant Excel version compatibility issues again this year. The formatting is off or missing.

When you open up a Data Pack on Excel 2010 what most of USAID has, you get the following error message.

![image](https://user-images.githubusercontent.com/8933069/72073514-13779300-32be-11ea-85bb-ce9515f56bf4.png)

If you hit yes to process and load the file, you get this message

![image](https://user-images.githubusercontent.com/8933069/72073574-2c804400-32be-11ea-89f8-c9aa30f49b52.png)

So off the bat, there are formatting issues

Like this  on the landing page
![image](https://user-images.githubusercontent.com/8933069/72073688-65b8b400-32be-11ea-9368-ac07fdd4e6b2.png)

Or this with unhidden rows
![image](https://user-images.githubusercontent.com/8933069/72073706-723d0c80-32be-11ea-8777-55eeda48b327.png)

Or this with missing conditional formatting
![image](https://user-images.githubusercontent.com/8933069/72073951-f98a8000-32be-11ea-9885-40a9f9f97d92.png)

More substantively, we're seeing some issues with formulas.

![image](https://user-images.githubusercontent.com/8933069/72073781-9c8eca00-32be-11ea-9cbc-c55c4ab04370.png)

The above may be partially resolved if there were SPECTRUM data loaded in. But, I think there are some formula issues.  Excel 2010 is not recognizing the formalua "=_xlfn.IFNA(". Excel 2010 doesn't have "IFNA" only "IFERROR" The [MS support page](https://support.office.com/en-us/article/issue-an-xlfn-prefix-is-displayed-in-front-of-a-formula-882f1ef7-68fb-4fcd-8d54-9fbb77fd5025) shows that `_xlfn` is added to function that are no backwards compatible. The only resolution is to remove the unsupported function.

![image](https://user-images.githubusercontent.com/8933069/72074109-4c643780-32bf-11ea-9a33-93c751f2beee.png)

That's all I've found so far, but I wanted to raise the compatibility concerns.

**Comment by sam-bao** [comment]
@achafetz 

We are not able to continue supporting Excel 2010 for COP 20 data packs. Also worth noting, Microsoft discontinues support for Office 2010 this year as well (https://docs.microsoft.com/en-us/deployoffice/office-2010-end-support-roadmap).
